services:
  blogmanagementsystem.keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: blogmanagementsystem.keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "6060:8080"
    command: start-dev
    volumes:
      - ./.containers/keycloak_data:/opt/keycloak/data
  blogmanagementsystem.postgres:
    image: postgres:17.2
    container_name: blogmanagementsystem.postgres
    environment:
      - POSTGRES_DB=BlogManagementSystemDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
  blogmanagementsystem.presentation:
    image: ${DOCKER_REGISTRY-}blogmanagementsystempresentation
    container_name: blogmanagementsystem.presentation
    build:
      context: .
      dockerfile: BlogManagementSystem.Presentation/Dockerfile
    environment:
      - ConnectionStrings__Database=Server=blogmanagementsystem.postgres;Port=5432;Database=BlogManagementSystemDb;User Id=postgres;Password=postgres;Include Error Detail=true    
      - Keycloak__resource=blog-app-client-docker    
      - Keycloak__credentials__secret=jYzdEgEssQ0RbbRP0PDNXjmDdi1SWugr
    depends_on:
#      - blogmanagementsystem.keycloak
      - blogmanagementsystem.postgres